version: 2
jobs:
  build:
    working_directory: ~/ng
    docker:
      - image: angular/ngcontainer:0.0.1
    steps:
      - checkout

      - restore_cache:
          key: angular_bazel_example-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: bazel info release
      - run: bazel run @yarn//:yarn
      # Workaround https://github.com/bazelbuild/bazel/issues/3645
      - run: timeout 30 bazel build ... || (bazel shutdown; timeout 30 bazel build ... || (bazel shutdown; bazel build ...))

      - save_cache:
          key: angular_bazel_example-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"